const mix = require('laravel-mix');
const path = require('path');

const config = {
    npmDir: './node_modules',
    public: './public',
    sass: './resources/sass',
    vueAdmin: './resources/js/admin',
    vueApp: './resources/js/app',
    images: './resources/images',
};

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
    .js(config.vueAdmin + '/main.js', config.public + '/js/admin/main.js')
    .vue()
    .sass(config.sass + '/admin/styles.scss', config.public + '/css/admin/styles.css');

mix
    .js(config.vueApp + '/main.js', config.public + '/js/app/main.js')
    .vue()
    .sass(config.sass + '/app/styles.scss', config.public + '/css/app/styles.css');

mix.copyDirectory(config.images, config.public + '/images');

mix.webpackConfig({
    resolve: {
        alias: {
            Admin: path.resolve(__dirname, 'resources/js/admin'),
            AdminModules: path.resolve(__dirname, 'resources/js/admin/modules'),
            App: path.resolve(__dirname, 'resources/js/app'),
            Modules: path.resolve(__dirname, 'resources/js/app/modules'),
            Static: path.resolve(__dirname, 'resources/static'),
            Foundation: path.resolve(__dirname, 'resources/js/foundation'),
        },
    },
});

// Full API
// mix.js(src, output);
// mix.react(src, output); <-- Identical to mix.js(), but registers React Babel compilation.
// mix.preact(src, output); <-- Identical to mix.js(), but registers Preact compilation.
// mix.coffee(src, output); <-- Identical to mix.js(), but registers CoffeeScript compilation.
// mix.ts(src, output); <-- TypeScript support. Requires tsconfig.json to exist in the same folder as webpack.mix.js
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.stylus(src, output);
// mix.postCss(src, output, [require('postcss-some-plugin')()]);
// mix.browserSync('my-site.test');
// mix.combine(files, destination);
// mix.babel(files, destination); <-- Identical to mix.combine(), but also includes Babel compilation.
// mix.copy(from, to);
// mix.copyDirectory(fromDir, toDir);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.setResourceRoot('prefix/for/resource/locators');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
// mix.babelConfig({}); <-- Merge extra Babel configuration (plugins, etc.) with Mix's default.
// mix.then(function () {}) <-- Will be triggered each time Webpack finishes building.
// mix.override(function (webpackConfig) {}) <-- Will be triggered once the webpack config object has been fully generated by Mix.
// mix.dump(); <-- Dump the generated webpack config object to the console.
// mix.extend(name, handler) <-- Extend Mix's API with your own components.
// mix.options({
//   extractVueStyles: false, // Extract .vue component styling to file, rather than inline.
//   globalVueStyles: file, // Variables file to be imported in every component.
//   processCssUrls: true, // Process/optimize relative stylesheet url()'s. Set to false, if you don't want them touched.
//   purifyCss: false, // Remove unused CSS selectors.
//   terser: {}, // Terser-specific options. https://github.com/webpack-contrib/terser-webpack-plugin#options
//   postCss: [] // Post-CSS options: https://github.com/postcss/postcss/blob/master/docs/plugins.md
// });
