<?php
namespace App\Repositories;

use App\Models\Type;
use App\Repositories\Traits\GetById;
use App\Repositories\Traits\Vars;
use Illuminate\Support\Arr;

class TypeRepository extends BaseRepository {

    use Vars, GetById;

    /**
     * model
     *
     * @return string
     */
    public function model()
    {
        return Type::class;
    }

    public function create(array $attributes)
    {
        $attributes = Arr::only(
            $attributes,
            ['title', 'name', 'status', 'type', 'has_parent', 'child_of', 'structure', 'fields']
        );

        return parent::create($attributes);
    }

    public function getByName($name)
    {
        $type = $this->getVarByField('name', $name);

        if(!$type) {
            $type = $this->findByField('name', $name)->first();

            if(!$type) {
                return null;
            }
        }

        $this->setVar($type->id, $type);

        return $type;
    }

    public function update(array $attributes, $id)
    {
        $attributes = Arr::only(
            $attributes,
            ['title', 'name', 'status', 'type', 'has_parent', 'child_of', 'structure', 'fields']
        );

        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function getActiveList()
    {
        return $this->findWhere(['status' => 1], ['id', 'title', 'name', 'type', 'child_of']);
    }

    public function getByType(string $type)
    {
        return $this->findWhere(['status' => 1, 'type' => $type], ['id', 'title', 'name']);
    }

    public function categories()
    {
        return $this->findWhere(['status' => 1, 'type' => Type::TYPE_CATEGORY], ['id', 'name']);
    }

    public function notUsedCategories($id = 0)
    {
        $usedCategories = $this
            ->findWhere([['child_of', '<>', 0], 'type' => Type::TYPE_POST], ['child_of'])
            ->pluck('child_of')
            ->filter(function ($childOf) use ($id) {
                return $childOf != $id;
            })
            ->toArray();
        return $this
            ->whereNotIn('id', $usedCategories)
            ->where('status', 1)
            ->where('type', Type::TYPE_CATEGORY)
            ->get(['id', 'name', 'title']);
    }
}
